### ISSUE TITLE
Group agreements

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1532]
https://www.figma.com/file/WlhwWUHxqDKBIf2E0jHqlm/User-%26-Group-Agreements?type=design&node-id=0-1&mode=design&t=BJnWyhVPVcZZaiPC-0

- [ ] Show on group about page, both external facing and internal About page
- [x] When requesting to join have them check each agreement
- [x] At bottom have the checkbox that says I agree to all of these. 
- [x] Show when user is first joining a group, if they have not agreed to them
- [ ] If new agreement is added, we pop up agreements again with new one unchecked (later)
