### ISSUE TITLE
Group roles and responsibilities

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1533]
https://www.figma.com/file/jaHPBbpLu2Pbiywr3Y1inx/Roles-%26-Responsibilities?type=design&node-id=1-2&mode=design&t=DTA7UBeNKer3zW9B-0

Copy here: https://docs.google.com/document/d/1EUiiTtIyGAIEZRwF1uJtDk-FAyj3HchRZ5Kwf62cSv8/edit#heading=h.ckiuqo2nxeoz

- [x] Show responsibilities connected to people's roles
- [x] Only let Managers access Group settings
- [x] Let people with Add Members responsibility access the invite page
- [x] Let people with the Remove Members remove members
- [x] Let people with the Remove Content responsibility moderate content (and get flag messages)
- [x] Let people with assign roles and responsibilities access that settings page? Only ones they already have unless they are admin? (This is a bonus/later thing)

**Comment by thomasgwatson** [comment]
Follow on checks required:

Global switch from 'moderators' (groupMembership.role) to common-role table 'manager' (recorded through a join table)
- [ ] Write data-migration of all current moderators to common role managers (custom moderator names are getting nerfed)
- [ ] Some location accuracy preferences check moderator status. Need to confirm that has been accounted for with switch to
- [ ] Remove EVO UI for moderators once data migration is done

General follow-up
- [ ] Testing for moderator role in the tests was much simpler to setup. Write concise snippet to add to many test setups to give mod status
- [ ] Verify all TODO RESP references in hylo-node are taken care of
- [ ] Verify all TODO RESP references in hylo-evo are taken care of

**Comment by tibetsprague** [comment]
- [ ] Allow for changing emoji (and name?) of common roles in groups?

**Comment by thomasgwatson** [comment]
Is the about functionality something like: allow the common roles to be used as templates for new group roles? As it stands, its already very fast to defacto create stand-ins for the common roles, I don't think we'll improve the UX much by adding "templates"

**Comment by tibetsprague** [comment]
hmm, no its just about changing the name of the common roles in a group so you dont have to have two duplicate roles you are choosing between when assigning to someone, which could be confusing. however it does add a lot of complexity to enable changing the name/icon of a common role in a group, so im not sure its worth it right now
