### ISSUE TITLE
Proposal post type

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1564]
Most up to date details here: https://docs.google.com/document/d/1EUiiTtIyGAIEZRwF1uJtDk-FAyj3HchRZ5Kwf62cSv8/edit#heading=h.j8sxm8kc5x8

https://www.figma.com/file/H3WNvkSDPvLsWKQqHIUHRc/Proposal-Post-Type?type=design&node-id=0%3A1&mode=design&t=jfMzRN7jEsDOEP5g-1

- [x] Ability to create proposal posts
- - [x] Set quorum
- - [x] Setup proposal options
- - [x] Templates/shortcuts to different voting options that we offer as defaults
- [ ] Display of proposals, including voting options and # of votes for each option. How do we want to display vote counts? Need designs.
- [ ] Ability to vote on them by choosing options, until the proposal closes. And you can leave a comment as you vote which shows up as a comment on the post that also includes what option the person voted on at the front of the comment somehow
- [ ] Ability for post creator to change the state of the proposal to discussion phase, voting phase, or complete. And outcome to passed or failed. 
- [ ] New Governance view that shows all current open proposals and also past proposals with whether the passed or failed or quorum not reached 
- [ ] Show on proposal whether quorum of votes needed for proposal to complete has been achieved or not (and how many more needed)
- [ ] Proposals cant be edited in voting phase

**Comment by tibetsprague** [comment]
more conversation here: https://docs.google.com/document/d/1EUiiTtIyGAIEZRwF1uJtDk-FAyj3HchRZ5Kwf62cSv8/edit

**Comment by thomasgwatson** [comment]
Mobile: voting only for now

Manual switch isn't necessary for first version
Open voting state

Editing start and end dates is possible but might have complications

Stick with emoji and description, in lieu of full-description or tool-tip

1) who can see and who can vote question: how do we track this in the backend
- Keep this as a separate ticket

Multi-voting is a nice-to-have; user gets 5 votes, across options all the options
