### ISSUE TITLE
MVP of Collective/Community Moderation

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1647]
- [x] Flag content button leads to new Flagging detail UI
- [ ] Flagging detail UI includes
  - [x] List of platform agreements (expandable)
  - [x] List of group agreements (expandable)
  - [x] Ability to checkbox an agreement
  - [x] Text field For entering why (compulsory)
  - [x] Submit button
- [x] Moderation log is added to group navigation
- [x] Moderation log is scoped to group
- [ ] Moderation log items include
  - [x] Link to the post in question
  - [x] List of flags of post
    - [x] agreements that are allegedly violated and text explanation
  - [ ] reporters as anonymous? can be seen by admins? Can elect to self-disclose identity?
  - [ ] Users of the group with the 'manage content' responsibility can see several action buttons; remove content from group, clear flags
  - [ ] Reporters can see a button that says 'clear', to remove their report
- [ ] PostStream items are *all* impacts
- [x] Each type has a blur-overlay for flagged posts
- [x] Each blur overlay can be 'clicked-through' (saved in posts_users)
- [ ] PostDetail also has overlay but remembers if user has already clicked-thru
- [ ] PostCard and PostDetail also have a 'rehide' button (maybe?)
- [ ] PostDetail has a way to see flags on a post

- [ ] Author and moderators are notified that a post has been flagged from their group
- [ ] Moderators get a notification if a post in their group has been flagged in another group (extra)

Notifications/emails will have already gone out before content can be moderated.

**Comment by seltzered** [comment]
Cool to see a moderation log! Had a couple thoughts: 

Regarding "_reporters as anonymous? can be seen by admins? Can elect to self-disclose identity?_" I think the way another platform I've used is admins can see a reporter of a flagged post, but nobody else knows.

Sometimes a moderator may flag a post where the flagging action was debatable, and it can lead to a discussion among moderators to evolve their practices, sometimes discussion between the flagger and poster (coming towards understanding/apology), and possibly 'un-flag' the post.

**Member removals** The other thing that comes to mind is getting a notification about a member being removed and who did the removal, or if a member removed themself. May be beyond the scope of your MVP but was very much an issue in a previous space I was involved in.

**Moving posts between subgroups**: This may not translate the same way for the way Hylo is architected, but on another platform I use there is an an ability to move posts from one 'space' to another 'space'. This can sometimes be helpful for re-organizing posts after a group decides to make re-organize how it's categories work, and helpful if a user accidentally posts to the wrong group, but can also carry a risk if a moderator may want to bury a post that was perhaps made in a more Specific space and moves it into a much more open-ended General Discussions space. Saying all this to propose that **Moderators should get notification if a post is moved.**, but again not sure how this translates to the architecture of Hylo.

**Edited posts by moderators/admins**:  Hylo doesn't seem to allow for post editing from what I see so far, but another platform I've used allows for moderators to edit posts - sometimes this can be helpful/consensual for fixing broken links or adding contextual info (e.g. hashtags), but also comes with risks of a post getting edited in ways that that are privy to the moderator's preference. We used the edit feature quite regularly in lieu of 'co-authoring' for recurring events where information changed over time. Saying this just to mention that if Hylo ever supports edits moderators should get notification of post edits, ideally with a diff of the changes.

**Comment by thomasgwatson** [comment]
Thanks for the comments Vivek! This is very much our barebones first version of this. Seeing a log of the other sorts of actions is defo desirable. @KevinTriplett is also helping us out at the moment and very invested in making the moderation tooling appropriate for a community he wants to bring across from MN.

Currently, the anonymous reporting hides the id of the reporter from everyone BUT moderators.

We are hoping to have this pushed out to production in the next week or two
