### ISSUE TITLE
Add map view 

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#418]
Add a map view within Hylo to display all resources, requests and offers that have a location and are visible to the current user.  You can view this map within a community, network or all your communities. It is a new tab listed next to the feed and projects

https://www.figma.com/file/lh2DVGMh7CRdUsxF3k6vGI/Map-Improvements?node-id=128%3A384

- [x] Clicking on a pin on the map will bring up a card with info about the post: https://github.com/Hylozoic/hylo-evo/issues/445
- [x] Posts visible in the current map view are also listed along the side of the map in cards like Airbnb: https://github.com/Hylozoic/hylo-evo/issues/446
- [x] The map updates as its viewport moves or scales: https://github.com/Hylozoic/hylo-node/issues/479
- [x] The map can be searched using full text search and filtered by topic tag
- [x] Mousing over a post in the map shows tooltip: https://github.com/Hylozoic/hylo-evo/issues/444
- [x] Posts are clustered so at zoomed out scales they appear as grouped icons with a post count for the cluster: https://github.com/Hylozoic/hylo-evo/issues/450

**Comment by thomasgwatson** [comment]
https://www.figma.com/file/lh2DVGMh7CRdUsxF3k6vGI/Map-Improvements?node-id=8%3A1
https://www.hylo.com/all/p/30121

Linked some related commentary

**Comment by thomasgwatson** [comment]
@brodeur I have more specific design needs after reading into what is required for a clustered icon layer.

These layers need an icon atlas and a mapping to those icons. The icon atlas from the example icon-cluster map I have previously shared is below:

![image](https://user-images.githubusercontent.com/5193218/81092545-98159f00-8eb5-11ea-8993-87e07f4baeeb.png)

The layer then needs the mapping to be able to pick out the right icon to display. A subset of the mappings for the above icon

   {
     "marker-1": {
       "x": 0,
         "y": 0,
         "width": 128,
         "height": 128,
         "anchorY": 128
     },
     "marker-2": {
       "x": 128,
         "y": 0,
         "width": 128,
         "height": 128,
         "anchorY": 128
     },
   }

So, for one thing: we need every possible permutation of the icons packed into the library (unless we build an icon providing endpoint). We have to use png; css and svg belong to the DOM and these mapping libraries rely on webGL accelerated canvas elements.

The deck.gl maintainers suggest using something like [TexturePacker](https://www.codeandweb.com/texturepacker) to simplify the building of an Icon-atlas and mapping. 

Assuming that we don't need unique color combos (we don't need yellow-blue *and* blue-yellow) and that we alphabetically ordered the colors as identifiers we'd need a png for:
1. each color dot, without the grey background bubble ![Screen Shot 2020-05-05 at 11 25 20](https://user-images.githubusercontent.com/5193218/81102115-fc3f5f80-8ec3-11ea-8749-5ba8f52b7318.png)
   - (five: blue, red, green, yellow, purple)
2. each color pair, with grey background pill a la ![Screen Shot 2020-05-05 at 11 25 49](https://user-images.githubusercontent.com/5193218/81102043-e0d45480-8ec3-11ea-85c2-334adb853650.png)
   - (ten: blue-yellow, blue-green, blue-red, blue-purple, green-yellow, red-yellow, purple-yellow, green-red, green-purple, purple-red)
3. each color trio 
   - (ten: blue-green-red, blue-green-purple, blue-green-yellow, blue-red-purple, blue-red-yellow, blue-purple-yellow, green-purple-red, green-purple-yellow, green-red-yellow, red-purple-yellow) 
4. each color quad 
   - (five: blue-green-purple-red, blue-green-purple-yellow, blue-green-red-yellow, blue-purple-red-yellow and green-purple-red-yellow)
5. and then one for all five colors

For a grand total of 36 different icons. Separately, we would also be using a synced text layer, to write out the numbers of features hidden by a cluster.

Or.... we could have a more generic cluster icon and start with that.

If you want to go with fewer icons, I can roll with that. If you want leave the texturePacking to me, I can roll with that. I don't have the leet skills to make the pngs those...

**Comment by brodeur** [comment]
I'll prepare those Icons, @thomasgwatson! I'm working on the map today.. check my progress: 

https://www.figma.com/file/lh2DVGMh7CRdUsxF3k6vGI/Map-Improvements?node-id=0%3A1

Looking forward to connecting <3

**Comment by brodeur** [comment]
Can't the grey background bubble be CSS on the container? e.g. 

.pillContainer {
border-radius: 16px;
background-color: #23405b;
}

**Comment by tibetsprague** [comment]
im going to work on this: https://github.com/Hylozoic/hylo-node/issues/479
