### ISSUE TITLE
Add internationalization for multiple language support

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#972]
- [ ] Documenting every piece of text that isn’t post text/comments
- [x] Use https://react.i18next.com to support translations (https://github.com/Hylozoic/hylo-evo/issues/1371)
- [ ] Emails/Notifications (handled by https://github.com/Hylozoic/hylo-node/issues/888)
- [ ] Move text into a shared library that web and mobile can both draw from?
- [ ] Maybe switch from moment to Luxon to help with datetime stuff. https://github.com/Hylozoic/hylo-evo/issues/1346
- [ ] Decide how/where people set their language: during sign up, and in Personal Settings
- [ ] Decide whether to detect language based on location, and start using the detected language?
- [ ] Decide what languages we’ll start with and recruit translators to contribute translations. Spanish for sure
- [ ] Ask our community for open-source contributions of translations
